### ISSUE TITLE
Add supporting of unsubscribe event

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/uk.co.compucorp.civicrm.mailjet#1]
Mailjet returns event **unsub** but this extension doesn't support it. In this situation we'd like to do
- hold on the email
- opt out all contacts with this email

```
(
    [event] => unsub
    [time] => 1466693104
    [MessageID] => 18295957550356714
    [email] => eamil***sdf@g***.com
    [mj_campaign_id] => 10963932
    [mj_contact_id] => 8272659
    [customcampaign] => TRANS-"****" <info@domain.com>
    [mj_list_id] => 0
    [ip] => 127.0.0.4
    [geo] => 
    [agent] => List-Unsubscribe
)
```

**Comment by tttp** [comment]
To clarify: 
this example is for a transactional email (eg. receipt email sent after a donation), it ISN'T for civimail

For mass mailing, civi adds a list-unsubscribe header, that is NOT working, as it uses the mail account defined for the bounce (eg. bounce+{long_unique_id}@example.org), that mailjet isn't using.

Suggested fix for civimail:
- remove List-unsubscribe ( probably from a hook)
- fix civimail to put the url of the unsubscribe link (that always work) instead of the email unsubscribe, that doesn't

**Comment by tttp** [comment]
it's done, right?

**Comment by scardinius** [comment]
yes, done
