### ISSUE TITLE
Error handling - Extension throws 422

### ISSUE THREAD

**Issue by pbatroff** [WeMoveEU/uk.co.compucorp.civicrm.mailjet#17]
Currently, when an error occurs during a bounce event, specifically when civicrm cannot lookup the email address in the event, an `HTTP/1.1 422 unknown email address` is thrown, and the event is logged in the database.

This behavior can lead to a shutdown of the webhook, because Mailjet considers the behavior as an error, and tries again later. After ~24 hrs the webhook gets shut down, because in their system it doesn't work anymore. 

I don't think this behavior is correct, since we received the webhook, but had an internal error. We shouldn't throw a 422 here. Instead some internal report or something needs to be created. E.g. a cron job that monitors the log messages and send a mail to a configured admin address with the failed bounce event emails. 

This problem occurred with invalid emails in civicrm. There were broken email addresses in the system (imported), missing the `@` in the address. Mailjet did for some reason add `@localhost` in the end, leading to civicrm not being able to lookup the email address. after 24hrs the webhook shut down.

**Comment by rthouvenin** [comment]
Correct, the endpoint should return 200 OK in this use case.

We don't face the problem because we have an intermediate endpoint that queues all events for asynchronous processing through [consumer.php](https://github.com/WeMoveEU/uk.co.compucorp.civicrm.mailjet/blob/master/amqp/consumer.php#L70), which ignores the returned string and has special treatment only for exceptions.

**Comment by tttp** [comment]
I think we had similar problems with mailjet autocorrecting typos too or some weirdness.

Anyway, agree with @rthouvenin: we souldn't return a 4xx.
Instead of a report/monitoring system, it might be easier to create a "placeholder" contact with the unknown bounced email with a contact_source "unknown email that bounced with mailjet" and let the admins manage them like the other "normal" bounced contacts (ie. probably ignore them ;)

@pbatroff, would you have the time/skills to write that patch?

**Comment by tttp** [comment]
@rthouvenin was faster ;)
